<?php
/**
 * CapacityStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MyDHL\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * The version of the OpenAPI document: 2.11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Client\Model;

use \ArrayAccess;
use \MyDHL\Client\ObjectSerializer;

/**
 * CapacityStatus Class Doc Comment
 *
 * @category Class
 * @description Capacity information – only if additional call to SCMS was triggered
 * @package  MyDHL\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CapacityStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CapacityStatus';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sev' => 'string',
        'msg_clg' => 'string',
        'msg_c_igd' => 'string',
        'dsc' => 'string',
        'dtl_dsc' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sev' => null,
        'msg_clg' => null,
        'msg_c_igd' => null,
        'dsc' => null,
        'dtl_dsc' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sev' => false,
        'msg_clg' => false,
        'msg_c_igd' => false,
        'dsc' => false,
        'dtl_dsc' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sev' => 'sev',
        'msg_clg' => 'msgClg',
        'msg_c_igd' => 'msgCIgd',
        'dsc' => 'dsc',
        'dtl_dsc' => 'dtlDsc'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sev' => 'setSev',
        'msg_clg' => 'setMsgClg',
        'msg_c_igd' => 'setMsgCIgd',
        'dsc' => 'setDsc',
        'dtl_dsc' => 'setDtlDsc'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sev' => 'getSev',
        'msg_clg' => 'getMsgClg',
        'msg_c_igd' => 'getMsgCIgd',
        'dsc' => 'getDsc',
        'dtl_dsc' => 'getDtlDsc'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('sev', $data ?? [], null);
        $this->setIfExists('msg_clg', $data ?? [], null);
        $this->setIfExists('msg_c_igd', $data ?? [], null);
        $this->setIfExists('dsc', $data ?? [], null);
        $this->setIfExists('dtl_dsc', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sev
     *
     * @return string|null
     */
    public function getSev()
    {
        return $this->container['sev'];
    }

    /**
     * Sets sev
     *
     * @param string|null $sev Severity code
     *
     * @return self
     */
    public function setSev($sev)
    {
        if (is_null($sev)) {
            throw new \InvalidArgumentException('non-nullable sev cannot be null');
        }
        $this->container['sev'] = $sev;

        return $this;
    }

    /**
     * Gets msg_clg
     *
     * @return string|null
     */
    public function getMsgClg()
    {
        return $this->container['msg_clg'];
    }

    /**
     * Sets msg_clg
     *
     * @param string|null $msg_clg SCMS
     *
     * @return self
     */
    public function setMsgClg($msg_clg)
    {
        if (is_null($msg_clg)) {
            throw new \InvalidArgumentException('non-nullable msg_clg cannot be null');
        }
        $this->container['msg_clg'] = $msg_clg;

        return $this;
    }

    /**
     * Gets msg_c_igd
     *
     * @return string|null
     */
    public function getMsgCIgd()
    {
        return $this->container['msg_c_igd'];
    }

    /**
     * Sets msg_c_igd
     *
     * @param string|null $msg_c_igd SCMS Status code
     *
     * @return self
     */
    public function setMsgCIgd($msg_c_igd)
    {
        if (is_null($msg_c_igd)) {
            throw new \InvalidArgumentException('non-nullable msg_c_igd cannot be null');
        }
        $this->container['msg_c_igd'] = $msg_c_igd;

        return $this;
    }

    /**
     * Gets dsc
     *
     * @return string|null
     */
    public function getDsc()
    {
        return $this->container['dsc'];
    }

    /**
     * Sets dsc
     *
     * @param string|null $dsc SCMS Description of status code
     *
     * @return self
     */
    public function setDsc($dsc)
    {
        if (is_null($dsc)) {
            throw new \InvalidArgumentException('non-nullable dsc cannot be null');
        }
        $this->container['dsc'] = $dsc;

        return $this;
    }

    /**
     * Gets dtl_dsc
     *
     * @return string|null
     */
    public function getDtlDsc()
    {
        return $this->container['dtl_dsc'];
    }

    /**
     * Sets dtl_dsc
     *
     * @param string|null $dtl_dsc SCMS detailed description
     *
     * @return self
     */
    public function setDtlDsc($dtl_dsc)
    {
        if (is_null($dtl_dsc)) {
            throw new \InvalidArgumentException('non-nullable dtl_dsc cannot be null');
        }
        $this->container['dtl_dsc'] = $dtl_dsc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


