<?php
/**
 * OpeningHours
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MyDHL\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * The version of the OpenAPI document: 2.11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Client\Model;

use \ArrayAccess;
use \MyDHL\Client\ObjectSerializer;

/**
 * OpeningHours Class Doc Comment
 *
 * @category Class
 * @description Array of openingHours entities, each consisting of week day, opening time and closing time.
 * @package  MyDHL\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OpeningHours implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OpeningHours';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'opening_hours' => '\MyDHL\Client\Model\OpeningTime[]',
        'holiday_dates' => '\DateTime[]',
        'holidays_dates' => 'array<string,\DateTime[]>',
        'html' => 'string',
        'holiday_opening_hours_html' => 'string',
        'holidays' => '\MyDHL\Client\Model\Holidays'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'opening_hours' => null,
        'holiday_dates' => 'date',
        'holidays_dates' => 'date',
        'html' => null,
        'holiday_opening_hours_html' => null,
        'holidays' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'opening_hours' => false,
        'holiday_dates' => false,
        'holidays_dates' => false,
        'html' => false,
        'holiday_opening_hours_html' => false,
        'holidays' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'opening_hours' => 'openingHours',
        'holiday_dates' => 'holidayDates',
        'holidays_dates' => 'holidaysDates',
        'html' => 'html',
        'holiday_opening_hours_html' => 'holidayOpeningHoursHtml',
        'holidays' => 'holidays'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'opening_hours' => 'setOpeningHours',
        'holiday_dates' => 'setHolidayDates',
        'holidays_dates' => 'setHolidaysDates',
        'html' => 'setHtml',
        'holiday_opening_hours_html' => 'setHolidayOpeningHoursHtml',
        'holidays' => 'setHolidays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'opening_hours' => 'getOpeningHours',
        'holiday_dates' => 'getHolidayDates',
        'holidays_dates' => 'getHolidaysDates',
        'html' => 'getHtml',
        'holiday_opening_hours_html' => 'getHolidayOpeningHoursHtml',
        'holidays' => 'getHolidays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('opening_hours', $data ?? [], null);
        $this->setIfExists('holiday_dates', $data ?? [], null);
        $this->setIfExists('holidays_dates', $data ?? [], null);
        $this->setIfExists('html', $data ?? [], null);
        $this->setIfExists('holiday_opening_hours_html', $data ?? [], null);
        $this->setIfExists('holidays', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['opening_hours'] === null) {
            $invalidProperties[] = "'opening_hours' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets opening_hours
     *
     * @return \MyDHL\Client\Model\OpeningTime[]
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param \MyDHL\Client\Model\OpeningTime[] $opening_hours Multiple opening hours entities can exist for the same week day.
     *
     * @return self
     */
    public function setOpeningHours($opening_hours)
    {
        if (is_null($opening_hours)) {
            throw new \InvalidArgumentException('non-nullable opening_hours cannot be null');
        }
        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }

    /**
     * Gets holiday_dates
     *
     * @return \DateTime[]|null
     */
    public function getHolidayDates()
    {
        return $this->container['holiday_dates'];
    }

    /**
     * Sets holiday_dates
     *
     * @param \DateTime[]|null $holiday_dates Holiday details with date
     *
     * @return self
     */
    public function setHolidayDates($holiday_dates)
    {
        if (is_null($holiday_dates)) {
            throw new \InvalidArgumentException('non-nullable holiday_dates cannot be null');
        }
        $this->container['holiday_dates'] = $holiday_dates;

        return $this;
    }

    /**
     * Gets holidays_dates
     *
     * @return array<string,\DateTime[]>|null
     */
    public function getHolidaysDates()
    {
        return $this->container['holidays_dates'];
    }

    /**
     * Sets holidays_dates
     *
     * @param array<string,\DateTime[]>|null $holidays_dates Holiday details with date
     *
     * @return self
     */
    public function setHolidaysDates($holidays_dates)
    {
        if (is_null($holidays_dates)) {
            throw new \InvalidArgumentException('non-nullable holidays_dates cannot be null');
        }
        $this->container['holidays_dates'] = $holidays_dates;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html Obsolete. This is planned to be removed in future releases.
     *
     * @return self
     */
    public function setHtml($html)
    {
        if (is_null($html)) {
            throw new \InvalidArgumentException('non-nullable html cannot be null');
        }
        $this->container['html'] = $html;

        return $this;
    }

    /**
     * Gets holiday_opening_hours_html
     *
     * @return string|null
     */
    public function getHolidayOpeningHoursHtml()
    {
        return $this->container['holiday_opening_hours_html'];
    }

    /**
     * Sets holiday_opening_hours_html
     *
     * @param string|null $holiday_opening_hours_html Obsolete. This is planned to be removed in future releases.
     *
     * @return self
     */
    public function setHolidayOpeningHoursHtml($holiday_opening_hours_html)
    {
        if (is_null($holiday_opening_hours_html)) {
            throw new \InvalidArgumentException('non-nullable holiday_opening_hours_html cannot be null');
        }
        $this->container['holiday_opening_hours_html'] = $holiday_opening_hours_html;

        return $this;
    }

    /**
     * Gets holidays
     *
     * @return \MyDHL\Client\Model\Holidays|null
     */
    public function getHolidays()
    {
        return $this->container['holidays'];
    }

    /**
     * Sets holidays
     *
     * @param \MyDHL\Client\Model\Holidays|null $holidays holidays
     *
     * @return self
     */
    public function setHolidays($holidays)
    {
        if (is_null($holidays)) {
            throw new \InvalidArgumentException('non-nullable holidays cannot be null');
        }
        $this->container['holidays'] = $holidays;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


