<?php
/**
 * ServicePointCapabilities
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MyDHL\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * The version of the OpenAPI document: 2.11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Client\Model;

use \ArrayAccess;
use \MyDHL\Client\ObjectSerializer;

/**
 * ServicePointCapabilities Class Doc Comment
 *
 * @category Class
 * @description An entity that lists all capabilities of a Service Point.
 * @package  MyDHL\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServicePointCapabilities implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServicePointCapabilities';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'parking_available' => 'bool',
        'disabled_access' => 'bool',
        'shipment_drop_off' => 'bool',
        'shipment_collection' => 'bool',
        'international_shipping' => 'bool',
        'domestic_shipping' => 'bool',
        'account_shippers' => 'bool',
        'label_printing' => 'bool',
        'insurance' => 'bool',
        'import_charges' => 'bool',
        'packaging' => 'bool',
        'receiver_paid' => 'bool',
        'visa_program' => 'bool',
        'pay_with_cash' => 'bool',
        'pay_with_credit_card' => 'bool',
        'pay_with_cheque' => 'bool',
        'pay_with_mobile' => 'bool',
        'pay_with_pay_pal' => 'bool',
        'parking_title' => 'string',
        'disabled_access_title' => 'string',
        'piece_weight_limit' => 'float',
        'piece_weight_limit_unit' => 'string',
        'piece_dimensions_limit' => '\MyDHL\Client\Model\Dimensions',
        'piece_dimensions_limit_unit' => 'string',
        'piece_count_limit' => 'float',
        'account_prepaid_shippers' => 'bool',
        'prepaid_shippers' => 'bool',
        'pre_print_return_label' => 'bool',
        'label_free' => 'bool',
        'ppc_list' => 'string[]',
        'html' => 'string',
        'capability_codes' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'parking_available' => null,
        'disabled_access' => null,
        'shipment_drop_off' => null,
        'shipment_collection' => null,
        'international_shipping' => null,
        'domestic_shipping' => null,
        'account_shippers' => null,
        'label_printing' => null,
        'insurance' => null,
        'import_charges' => null,
        'packaging' => null,
        'receiver_paid' => null,
        'visa_program' => null,
        'pay_with_cash' => null,
        'pay_with_credit_card' => null,
        'pay_with_cheque' => null,
        'pay_with_mobile' => null,
        'pay_with_pay_pal' => null,
        'parking_title' => null,
        'disabled_access_title' => null,
        'piece_weight_limit' => null,
        'piece_weight_limit_unit' => null,
        'piece_dimensions_limit' => null,
        'piece_dimensions_limit_unit' => null,
        'piece_count_limit' => null,
        'account_prepaid_shippers' => null,
        'prepaid_shippers' => null,
        'pre_print_return_label' => null,
        'label_free' => null,
        'ppc_list' => null,
        'html' => null,
        'capability_codes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'parking_available' => false,
        'disabled_access' => false,
        'shipment_drop_off' => false,
        'shipment_collection' => false,
        'international_shipping' => false,
        'domestic_shipping' => false,
        'account_shippers' => false,
        'label_printing' => false,
        'insurance' => false,
        'import_charges' => false,
        'packaging' => false,
        'receiver_paid' => false,
        'visa_program' => false,
        'pay_with_cash' => false,
        'pay_with_credit_card' => false,
        'pay_with_cheque' => false,
        'pay_with_mobile' => false,
        'pay_with_pay_pal' => false,
        'parking_title' => false,
        'disabled_access_title' => false,
        'piece_weight_limit' => false,
        'piece_weight_limit_unit' => false,
        'piece_dimensions_limit' => false,
        'piece_dimensions_limit_unit' => false,
        'piece_count_limit' => false,
        'account_prepaid_shippers' => false,
        'prepaid_shippers' => false,
        'pre_print_return_label' => false,
        'label_free' => false,
        'ppc_list' => false,
        'html' => false,
        'capability_codes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parking_available' => 'parkingAvailable',
        'disabled_access' => 'disabledAccess',
        'shipment_drop_off' => 'shipmentDropOff',
        'shipment_collection' => 'shipmentCollection',
        'international_shipping' => 'internationalShipping',
        'domestic_shipping' => 'domesticShipping',
        'account_shippers' => 'accountShippers',
        'label_printing' => 'labelPrinting',
        'insurance' => 'insurance',
        'import_charges' => 'importCharges',
        'packaging' => 'packaging',
        'receiver_paid' => 'receiverPaid',
        'visa_program' => 'visaProgram',
        'pay_with_cash' => 'payWithCash',
        'pay_with_credit_card' => 'payWithCreditCard',
        'pay_with_cheque' => 'payWithCheque',
        'pay_with_mobile' => 'payWithMobile',
        'pay_with_pay_pal' => 'payWithPayPal',
        'parking_title' => 'parkingTitle',
        'disabled_access_title' => 'disabledAccessTitle',
        'piece_weight_limit' => 'pieceWeightLimit',
        'piece_weight_limit_unit' => 'pieceWeightLimitUnit',
        'piece_dimensions_limit' => 'pieceDimensionsLimit',
        'piece_dimensions_limit_unit' => 'pieceDimensionsLimitUnit',
        'piece_count_limit' => 'pieceCountLimit',
        'account_prepaid_shippers' => 'accountPrepaidShippers',
        'prepaid_shippers' => 'prepaidShippers',
        'pre_print_return_label' => 'prePrintReturnLabel',
        'label_free' => 'labelFree',
        'ppc_list' => 'ppcList',
        'html' => 'html',
        'capability_codes' => 'capabilityCodes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parking_available' => 'setParkingAvailable',
        'disabled_access' => 'setDisabledAccess',
        'shipment_drop_off' => 'setShipmentDropOff',
        'shipment_collection' => 'setShipmentCollection',
        'international_shipping' => 'setInternationalShipping',
        'domestic_shipping' => 'setDomesticShipping',
        'account_shippers' => 'setAccountShippers',
        'label_printing' => 'setLabelPrinting',
        'insurance' => 'setInsurance',
        'import_charges' => 'setImportCharges',
        'packaging' => 'setPackaging',
        'receiver_paid' => 'setReceiverPaid',
        'visa_program' => 'setVisaProgram',
        'pay_with_cash' => 'setPayWithCash',
        'pay_with_credit_card' => 'setPayWithCreditCard',
        'pay_with_cheque' => 'setPayWithCheque',
        'pay_with_mobile' => 'setPayWithMobile',
        'pay_with_pay_pal' => 'setPayWithPayPal',
        'parking_title' => 'setParkingTitle',
        'disabled_access_title' => 'setDisabledAccessTitle',
        'piece_weight_limit' => 'setPieceWeightLimit',
        'piece_weight_limit_unit' => 'setPieceWeightLimitUnit',
        'piece_dimensions_limit' => 'setPieceDimensionsLimit',
        'piece_dimensions_limit_unit' => 'setPieceDimensionsLimitUnit',
        'piece_count_limit' => 'setPieceCountLimit',
        'account_prepaid_shippers' => 'setAccountPrepaidShippers',
        'prepaid_shippers' => 'setPrepaidShippers',
        'pre_print_return_label' => 'setPrePrintReturnLabel',
        'label_free' => 'setLabelFree',
        'ppc_list' => 'setPpcList',
        'html' => 'setHtml',
        'capability_codes' => 'setCapabilityCodes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parking_available' => 'getParkingAvailable',
        'disabled_access' => 'getDisabledAccess',
        'shipment_drop_off' => 'getShipmentDropOff',
        'shipment_collection' => 'getShipmentCollection',
        'international_shipping' => 'getInternationalShipping',
        'domestic_shipping' => 'getDomesticShipping',
        'account_shippers' => 'getAccountShippers',
        'label_printing' => 'getLabelPrinting',
        'insurance' => 'getInsurance',
        'import_charges' => 'getImportCharges',
        'packaging' => 'getPackaging',
        'receiver_paid' => 'getReceiverPaid',
        'visa_program' => 'getVisaProgram',
        'pay_with_cash' => 'getPayWithCash',
        'pay_with_credit_card' => 'getPayWithCreditCard',
        'pay_with_cheque' => 'getPayWithCheque',
        'pay_with_mobile' => 'getPayWithMobile',
        'pay_with_pay_pal' => 'getPayWithPayPal',
        'parking_title' => 'getParkingTitle',
        'disabled_access_title' => 'getDisabledAccessTitle',
        'piece_weight_limit' => 'getPieceWeightLimit',
        'piece_weight_limit_unit' => 'getPieceWeightLimitUnit',
        'piece_dimensions_limit' => 'getPieceDimensionsLimit',
        'piece_dimensions_limit_unit' => 'getPieceDimensionsLimitUnit',
        'piece_count_limit' => 'getPieceCountLimit',
        'account_prepaid_shippers' => 'getAccountPrepaidShippers',
        'prepaid_shippers' => 'getPrepaidShippers',
        'pre_print_return_label' => 'getPrePrintReturnLabel',
        'label_free' => 'getLabelFree',
        'ppc_list' => 'getPpcList',
        'html' => 'getHtml',
        'capability_codes' => 'getCapabilityCodes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('parking_available', $data ?? [], null);
        $this->setIfExists('disabled_access', $data ?? [], null);
        $this->setIfExists('shipment_drop_off', $data ?? [], null);
        $this->setIfExists('shipment_collection', $data ?? [], null);
        $this->setIfExists('international_shipping', $data ?? [], null);
        $this->setIfExists('domestic_shipping', $data ?? [], null);
        $this->setIfExists('account_shippers', $data ?? [], null);
        $this->setIfExists('label_printing', $data ?? [], null);
        $this->setIfExists('insurance', $data ?? [], null);
        $this->setIfExists('import_charges', $data ?? [], null);
        $this->setIfExists('packaging', $data ?? [], null);
        $this->setIfExists('receiver_paid', $data ?? [], null);
        $this->setIfExists('visa_program', $data ?? [], null);
        $this->setIfExists('pay_with_cash', $data ?? [], null);
        $this->setIfExists('pay_with_credit_card', $data ?? [], null);
        $this->setIfExists('pay_with_cheque', $data ?? [], null);
        $this->setIfExists('pay_with_mobile', $data ?? [], null);
        $this->setIfExists('pay_with_pay_pal', $data ?? [], null);
        $this->setIfExists('parking_title', $data ?? [], null);
        $this->setIfExists('disabled_access_title', $data ?? [], null);
        $this->setIfExists('piece_weight_limit', $data ?? [], null);
        $this->setIfExists('piece_weight_limit_unit', $data ?? [], null);
        $this->setIfExists('piece_dimensions_limit', $data ?? [], null);
        $this->setIfExists('piece_dimensions_limit_unit', $data ?? [], null);
        $this->setIfExists('piece_count_limit', $data ?? [], null);
        $this->setIfExists('account_prepaid_shippers', $data ?? [], null);
        $this->setIfExists('prepaid_shippers', $data ?? [], null);
        $this->setIfExists('pre_print_return_label', $data ?? [], null);
        $this->setIfExists('label_free', $data ?? [], null);
        $this->setIfExists('ppc_list', $data ?? [], null);
        $this->setIfExists('html', $data ?? [], null);
        $this->setIfExists('capability_codes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parking_available
     *
     * @return bool|null
     */
    public function getParkingAvailable()
    {
        return $this->container['parking_available'];
    }

    /**
     * Sets parking_available
     *
     * @param bool|null $parking_available Indicates whether parking facility is available in the service point or not
     *
     * @return self
     */
    public function setParkingAvailable($parking_available)
    {
        if (is_null($parking_available)) {
            throw new \InvalidArgumentException('non-nullable parking_available cannot be null');
        }
        $this->container['parking_available'] = $parking_available;

        return $this;
    }

    /**
     * Gets disabled_access
     *
     * @return bool|null
     */
    public function getDisabledAccess()
    {
        return $this->container['disabled_access'];
    }

    /**
     * Sets disabled_access
     *
     * @param bool|null $disabled_access Indicates whether disabled access is available in the service point or not
     *
     * @return self
     */
    public function setDisabledAccess($disabled_access)
    {
        if (is_null($disabled_access)) {
            throw new \InvalidArgumentException('non-nullable disabled_access cannot be null');
        }
        $this->container['disabled_access'] = $disabled_access;

        return $this;
    }

    /**
     * Gets shipment_drop_off
     *
     * @return bool|null
     */
    public function getShipmentDropOff()
    {
        return $this->container['shipment_drop_off'];
    }

    /**
     * Sets shipment_drop_off
     *
     * @param bool|null $shipment_drop_off Indicates whether Shipment Drop Off is available in the service point or not
     *
     * @return self
     */
    public function setShipmentDropOff($shipment_drop_off)
    {
        if (is_null($shipment_drop_off)) {
            throw new \InvalidArgumentException('non-nullable shipment_drop_off cannot be null');
        }
        $this->container['shipment_drop_off'] = $shipment_drop_off;

        return $this;
    }

    /**
     * Gets shipment_collection
     *
     * @return bool|null
     */
    public function getShipmentCollection()
    {
        return $this->container['shipment_collection'];
    }

    /**
     * Sets shipment_collection
     *
     * @param bool|null $shipment_collection Indicates whether Shipment Collection is available in the service point or not
     *
     * @return self
     */
    public function setShipmentCollection($shipment_collection)
    {
        if (is_null($shipment_collection)) {
            throw new \InvalidArgumentException('non-nullable shipment_collection cannot be null');
        }
        $this->container['shipment_collection'] = $shipment_collection;

        return $this;
    }

    /**
     * Gets international_shipping
     *
     * @return bool|null
     */
    public function getInternationalShipping()
    {
        return $this->container['international_shipping'];
    }

    /**
     * Sets international_shipping
     *
     * @param bool|null $international_shipping Indicates whether International Shipping is available in the service point or not
     *
     * @return self
     */
    public function setInternationalShipping($international_shipping)
    {
        if (is_null($international_shipping)) {
            throw new \InvalidArgumentException('non-nullable international_shipping cannot be null');
        }
        $this->container['international_shipping'] = $international_shipping;

        return $this;
    }

    /**
     * Gets domestic_shipping
     *
     * @return bool|null
     */
    public function getDomesticShipping()
    {
        return $this->container['domestic_shipping'];
    }

    /**
     * Sets domestic_shipping
     *
     * @param bool|null $domestic_shipping Indicates whether Domestic Shipping is available in the service point or not
     *
     * @return self
     */
    public function setDomesticShipping($domestic_shipping)
    {
        if (is_null($domestic_shipping)) {
            throw new \InvalidArgumentException('non-nullable domestic_shipping cannot be null');
        }
        $this->container['domestic_shipping'] = $domestic_shipping;

        return $this;
    }

    /**
     * Gets account_shippers
     *
     * @return bool|null
     */
    public function getAccountShippers()
    {
        return $this->container['account_shippers'];
    }

    /**
     * Sets account_shippers
     *
     * @param bool|null $account_shippers Indicates whether Account Shipping is available in the service point or not
     *
     * @return self
     */
    public function setAccountShippers($account_shippers)
    {
        if (is_null($account_shippers)) {
            throw new \InvalidArgumentException('non-nullable account_shippers cannot be null');
        }
        $this->container['account_shippers'] = $account_shippers;

        return $this;
    }

    /**
     * Gets label_printing
     *
     * @return bool|null
     */
    public function getLabelPrinting()
    {
        return $this->container['label_printing'];
    }

    /**
     * Sets label_printing
     *
     * @param bool|null $label_printing Indicates whether Label Printing is available in the service point or not
     *
     * @return self
     */
    public function setLabelPrinting($label_printing)
    {
        if (is_null($label_printing)) {
            throw new \InvalidArgumentException('non-nullable label_printing cannot be null');
        }
        $this->container['label_printing'] = $label_printing;

        return $this;
    }

    /**
     * Gets insurance
     *
     * @return bool|null
     */
    public function getInsurance()
    {
        return $this->container['insurance'];
    }

    /**
     * Sets insurance
     *
     * @param bool|null $insurance Indicates whether Insurance facility is available in the service point or not
     *
     * @return self
     */
    public function setInsurance($insurance)
    {
        if (is_null($insurance)) {
            throw new \InvalidArgumentException('non-nullable insurance cannot be null');
        }
        $this->container['insurance'] = $insurance;

        return $this;
    }

    /**
     * Gets import_charges
     *
     * @return bool|null
     */
    public function getImportCharges()
    {
        return $this->container['import_charges'];
    }

    /**
     * Sets import_charges
     *
     * @param bool|null $import_charges Indicates whether Import Charges is applicable in the service point or not
     *
     * @return self
     */
    public function setImportCharges($import_charges)
    {
        if (is_null($import_charges)) {
            throw new \InvalidArgumentException('non-nullable import_charges cannot be null');
        }
        $this->container['import_charges'] = $import_charges;

        return $this;
    }

    /**
     * Gets packaging
     *
     * @return bool|null
     */
    public function getPackaging()
    {
        return $this->container['packaging'];
    }

    /**
     * Sets packaging
     *
     * @param bool|null $packaging Indicates whether Packaging facility is available in the service point or not
     *
     * @return self
     */
    public function setPackaging($packaging)
    {
        if (is_null($packaging)) {
            throw new \InvalidArgumentException('non-nullable packaging cannot be null');
        }
        $this->container['packaging'] = $packaging;

        return $this;
    }

    /**
     * Gets receiver_paid
     *
     * @return bool|null
     */
    public function getReceiverPaid()
    {
        return $this->container['receiver_paid'];
    }

    /**
     * Sets receiver_paid
     *
     * @param bool|null $receiver_paid Indicates whether Receiver Paying option is available in the service point or not
     *
     * @return self
     */
    public function setReceiverPaid($receiver_paid)
    {
        if (is_null($receiver_paid)) {
            throw new \InvalidArgumentException('non-nullable receiver_paid cannot be null');
        }
        $this->container['receiver_paid'] = $receiver_paid;

        return $this;
    }

    /**
     * Gets visa_program
     *
     * @return bool|null
     */
    public function getVisaProgram()
    {
        return $this->container['visa_program'];
    }

    /**
     * Sets visa_program
     *
     * @param bool|null $visa_program Indicates whether VISA program is applicable in the service point or not
     *
     * @return self
     */
    public function setVisaProgram($visa_program)
    {
        if (is_null($visa_program)) {
            throw new \InvalidArgumentException('non-nullable visa_program cannot be null');
        }
        $this->container['visa_program'] = $visa_program;

        return $this;
    }

    /**
     * Gets pay_with_cash
     *
     * @return bool|null
     */
    public function getPayWithCash()
    {
        return $this->container['pay_with_cash'];
    }

    /**
     * Sets pay_with_cash
     *
     * @param bool|null $pay_with_cash Indicates whether pay by cash option is available in the service point or not
     *
     * @return self
     */
    public function setPayWithCash($pay_with_cash)
    {
        if (is_null($pay_with_cash)) {
            throw new \InvalidArgumentException('non-nullable pay_with_cash cannot be null');
        }
        $this->container['pay_with_cash'] = $pay_with_cash;

        return $this;
    }

    /**
     * Gets pay_with_credit_card
     *
     * @return bool|null
     */
    public function getPayWithCreditCard()
    {
        return $this->container['pay_with_credit_card'];
    }

    /**
     * Sets pay_with_credit_card
     *
     * @param bool|null $pay_with_credit_card Indicates whether pay with credit card option is available in the service point or not
     *
     * @return self
     */
    public function setPayWithCreditCard($pay_with_credit_card)
    {
        if (is_null($pay_with_credit_card)) {
            throw new \InvalidArgumentException('non-nullable pay_with_credit_card cannot be null');
        }
        $this->container['pay_with_credit_card'] = $pay_with_credit_card;

        return $this;
    }

    /**
     * Gets pay_with_cheque
     *
     * @return bool|null
     */
    public function getPayWithCheque()
    {
        return $this->container['pay_with_cheque'];
    }

    /**
     * Sets pay_with_cheque
     *
     * @param bool|null $pay_with_cheque Indicates whether pay with cheque option is available in the service point or not
     *
     * @return self
     */
    public function setPayWithCheque($pay_with_cheque)
    {
        if (is_null($pay_with_cheque)) {
            throw new \InvalidArgumentException('non-nullable pay_with_cheque cannot be null');
        }
        $this->container['pay_with_cheque'] = $pay_with_cheque;

        return $this;
    }

    /**
     * Gets pay_with_mobile
     *
     * @return bool|null
     */
    public function getPayWithMobile()
    {
        return $this->container['pay_with_mobile'];
    }

    /**
     * Sets pay_with_mobile
     *
     * @param bool|null $pay_with_mobile Indicates whether pay with mobile option is available in the service point or not
     *
     * @return self
     */
    public function setPayWithMobile($pay_with_mobile)
    {
        if (is_null($pay_with_mobile)) {
            throw new \InvalidArgumentException('non-nullable pay_with_mobile cannot be null');
        }
        $this->container['pay_with_mobile'] = $pay_with_mobile;

        return $this;
    }

    /**
     * Gets pay_with_pay_pal
     *
     * @return bool|null
     */
    public function getPayWithPayPal()
    {
        return $this->container['pay_with_pay_pal'];
    }

    /**
     * Sets pay_with_pay_pal
     *
     * @param bool|null $pay_with_pay_pal Indicates whether pay with paypal option is available in the service point or not
     *
     * @return self
     */
    public function setPayWithPayPal($pay_with_pay_pal)
    {
        if (is_null($pay_with_pay_pal)) {
            throw new \InvalidArgumentException('non-nullable pay_with_pay_pal cannot be null');
        }
        $this->container['pay_with_pay_pal'] = $pay_with_pay_pal;

        return $this;
    }

    /**
     * Gets parking_title
     *
     * @return string|null
     */
    public function getParkingTitle()
    {
        return $this->container['parking_title'];
    }

    /**
     * Sets parking_title
     *
     * @param string|null $parking_title Title for the parking icon
     *
     * @return self
     */
    public function setParkingTitle($parking_title)
    {
        if (is_null($parking_title)) {
            throw new \InvalidArgumentException('non-nullable parking_title cannot be null');
        }
        $this->container['parking_title'] = $parking_title;

        return $this;
    }

    /**
     * Gets disabled_access_title
     *
     * @return string|null
     */
    public function getDisabledAccessTitle()
    {
        return $this->container['disabled_access_title'];
    }

    /**
     * Sets disabled_access_title
     *
     * @param string|null $disabled_access_title Title for the disable wheel chair icon
     *
     * @return self
     */
    public function setDisabledAccessTitle($disabled_access_title)
    {
        if (is_null($disabled_access_title)) {
            throw new \InvalidArgumentException('non-nullable disabled_access_title cannot be null');
        }
        $this->container['disabled_access_title'] = $disabled_access_title;

        return $this;
    }

    /**
     * Gets piece_weight_limit
     *
     * @return float|null
     */
    public function getPieceWeightLimit()
    {
        return $this->container['piece_weight_limit'];
    }

    /**
     * Sets piece_weight_limit
     *
     * @param float|null $piece_weight_limit Piece Weight Limit
     *
     * @return self
     */
    public function setPieceWeightLimit($piece_weight_limit)
    {
        if (is_null($piece_weight_limit)) {
            throw new \InvalidArgumentException('non-nullable piece_weight_limit cannot be null');
        }
        $this->container['piece_weight_limit'] = $piece_weight_limit;

        return $this;
    }

    /**
     * Gets piece_weight_limit_unit
     *
     * @return string|null
     */
    public function getPieceWeightLimitUnit()
    {
        return $this->container['piece_weight_limit_unit'];
    }

    /**
     * Sets piece_weight_limit_unit
     *
     * @param string|null $piece_weight_limit_unit Enumeration (KG or LB)
     *
     * @return self
     */
    public function setPieceWeightLimitUnit($piece_weight_limit_unit)
    {
        if (is_null($piece_weight_limit_unit)) {
            throw new \InvalidArgumentException('non-nullable piece_weight_limit_unit cannot be null');
        }
        $this->container['piece_weight_limit_unit'] = $piece_weight_limit_unit;

        return $this;
    }

    /**
     * Gets piece_dimensions_limit
     *
     * @return \MyDHL\Client\Model\Dimensions|null
     */
    public function getPieceDimensionsLimit()
    {
        return $this->container['piece_dimensions_limit'];
    }

    /**
     * Sets piece_dimensions_limit
     *
     * @param \MyDHL\Client\Model\Dimensions|null $piece_dimensions_limit piece_dimensions_limit
     *
     * @return self
     */
    public function setPieceDimensionsLimit($piece_dimensions_limit)
    {
        if (is_null($piece_dimensions_limit)) {
            throw new \InvalidArgumentException('non-nullable piece_dimensions_limit cannot be null');
        }
        $this->container['piece_dimensions_limit'] = $piece_dimensions_limit;

        return $this;
    }

    /**
     * Gets piece_dimensions_limit_unit
     *
     * @return string|null
     */
    public function getPieceDimensionsLimitUnit()
    {
        return $this->container['piece_dimensions_limit_unit'];
    }

    /**
     * Sets piece_dimensions_limit_unit
     *
     * @param string|null $piece_dimensions_limit_unit Enumeration (CM or IN)
     *
     * @return self
     */
    public function setPieceDimensionsLimitUnit($piece_dimensions_limit_unit)
    {
        if (is_null($piece_dimensions_limit_unit)) {
            throw new \InvalidArgumentException('non-nullable piece_dimensions_limit_unit cannot be null');
        }
        $this->container['piece_dimensions_limit_unit'] = $piece_dimensions_limit_unit;

        return $this;
    }

    /**
     * Gets piece_count_limit
     *
     * @return float|null
     */
    public function getPieceCountLimit()
    {
        return $this->container['piece_count_limit'];
    }

    /**
     * Sets piece_count_limit
     *
     * @param float|null $piece_count_limit Number (integer)
     *
     * @return self
     */
    public function setPieceCountLimit($piece_count_limit)
    {
        if (is_null($piece_count_limit)) {
            throw new \InvalidArgumentException('non-nullable piece_count_limit cannot be null');
        }
        $this->container['piece_count_limit'] = $piece_count_limit;

        return $this;
    }

    /**
     * Gets account_prepaid_shippers
     *
     * @return bool|null
     */
    public function getAccountPrepaidShippers()
    {
        return $this->container['account_prepaid_shippers'];
    }

    /**
     * Sets account_prepaid_shippers
     *
     * @param bool|null $account_prepaid_shippers Account prepaid shippers
     *
     * @return self
     */
    public function setAccountPrepaidShippers($account_prepaid_shippers)
    {
        if (is_null($account_prepaid_shippers)) {
            throw new \InvalidArgumentException('non-nullable account_prepaid_shippers cannot be null');
        }
        $this->container['account_prepaid_shippers'] = $account_prepaid_shippers;

        return $this;
    }

    /**
     * Gets prepaid_shippers
     *
     * @return bool|null
     */
    public function getPrepaidShippers()
    {
        return $this->container['prepaid_shippers'];
    }

    /**
     * Sets prepaid_shippers
     *
     * @param bool|null $prepaid_shippers Prepaid shippers
     *
     * @return self
     */
    public function setPrepaidShippers($prepaid_shippers)
    {
        if (is_null($prepaid_shippers)) {
            throw new \InvalidArgumentException('non-nullable prepaid_shippers cannot be null');
        }
        $this->container['prepaid_shippers'] = $prepaid_shippers;

        return $this;
    }

    /**
     * Gets pre_print_return_label
     *
     * @return bool|null
     */
    public function getPrePrintReturnLabel()
    {
        return $this->container['pre_print_return_label'];
    }

    /**
     * Sets pre_print_return_label
     *
     * @param bool|null $pre_print_return_label Pre-printed return label
     *
     * @return self
     */
    public function setPrePrintReturnLabel($pre_print_return_label)
    {
        if (is_null($pre_print_return_label)) {
            throw new \InvalidArgumentException('non-nullable pre_print_return_label cannot be null');
        }
        $this->container['pre_print_return_label'] = $pre_print_return_label;

        return $this;
    }

    /**
     * Gets label_free
     *
     * @return bool|null
     */
    public function getLabelFree()
    {
        return $this->container['label_free'];
    }

    /**
     * Sets label_free
     *
     * @param bool|null $label_free Indicates whether this particular service point can handle label free shipments or not
     *
     * @return self
     */
    public function setLabelFree($label_free)
    {
        if (is_null($label_free)) {
            throw new \InvalidArgumentException('non-nullable label_free cannot be null');
        }
        $this->container['label_free'] = $label_free;

        return $this;
    }

    /**
     * Gets ppc_list
     *
     * @return string[]|null
     */
    public function getPpcList()
    {
        return $this->container['ppc_list'];
    }

    /**
     * Sets ppc_list
     *
     * @param string[]|null $ppc_list PPC list.
     *
     * @return self
     */
    public function setPpcList($ppc_list)
    {
        if (is_null($ppc_list)) {
            throw new \InvalidArgumentException('non-nullable ppc_list cannot be null');
        }
        $this->container['ppc_list'] = $ppc_list;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html Obsolete. This is planned to be removed in future releases.
     *
     * @return self
     */
    public function setHtml($html)
    {
        if (is_null($html)) {
            throw new \InvalidArgumentException('non-nullable html cannot be null');
        }
        $this->container['html'] = $html;

        return $this;
    }

    /**
     * Gets capability_codes
     *
     * @return string|null
     */
    public function getCapabilityCodes()
    {
        return $this->container['capability_codes'];
    }

    /**
     * Sets capability_codes
     *
     * @param string|null $capability_codes PPC codes available for this service point
     *
     * @return self
     */
    public function setCapabilityCodes($capability_codes)
    {
        if (is_null($capability_codes)) {
            throw new \InvalidArgumentException('non-nullable capability_codes cannot be null');
        }
        $this->container['capability_codes'] = $capability_codes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


